# Common prompt to include for every sample
common_prompt = "High-quality, realistic sound"
title = "forest"

prompts = [
# 昼間の環境音
["ENV_Day_BirdsChirping", "鳥のさえずり／春の森の昼", "Morning birds chirping in spring forest"],
["ENV_Day_InsectsBuzz", "昆虫の羽音／夏の森の昼", "Insects buzzing in summer forest"],
["ENV_Day_LeafRustle", "木漏れ日の葉擦れ音", "Sunlit leaves rustling"],
["ENV_Day_TreeCreak", "木の軋み音／緩やかな風", "Gentle wind creaking branches"],
["ENV_Day_SquirrelScurry", "リスの走る音", "Squirrel scurrying"],
["ENV_Day_MushroomSporeWind", "キノコの胞子飛散音", "Mushroom spores drifting"],
["ENV_Day_WoodpeckerTap", "キツツキの突く音", "Woodpecker tapping"],
["ENV_Day_ForestAmbience", "森全体の環境音／昼", "Overall forest ambience—day"],
["ENV_Day_CicadaSong", "セミの鳴き声", "Cicadas singing"],
["ENV_Day_MossyGroundShift", "苔むした地面の足跡", "Mossy ground shifting"],
["ENV_Day_SunbeamRustle", "日差しの中の葉擦れ音", "Rustle under sunbeams"],
["ENV_Day_DappledWind", "木漏れ日を揺らす風音", "Dappled sunlight wind"],
["ENV_Day_ButterflyFlutter", "蝶の羽ばたき", "Butterfly wings fluttering"],
# 夜間の環境音
["ENV_Night_CicadaChorus", "夜のセミの大合唱", "Night cicada chorus"],
["ENV_Night_CricketChirp", "コオロギの鳴き声", "Crickets chirping"],
["ENV_Night_FrogsCroak", "カエルの鳴き声／遠景", "Distant frogs croaking"],
["ENV_Night_OwlHoot", "フクロウの鳴き声", "Owl hooting"],
["ENV_Night_BatEchoes", "コウモリの鳴き声", "Bat echolocation calls"],
["ENV_Night_MushroomGlowAmbience", "蛍光キノコの淡い響き", "Soft glow of bioluminescent mushrooms"],
["ENV_Night_ForestAmbience", "森全体の環境音／夜", "Overall forest ambience—night"],
["ENV_Night_FireflyWhisper", "蛍の飛行音", "Fireflies buzzing"],
["ENV_Night_OwlWings", "フクロウの羽ばたき", "Owl wings flapping"],
["ENV_Night_DistantWolfHowl", "遠くの狼の遠吠え", "Distant wolf howling"],
["ENV_Night_PineNeedleRustle", "松葉のさざめき", "Pine needle rustle"],
["ENV_Night_GlowMushroomDrip", "キノコ滴る水音", "Mushroom water dripping"],
["ENV_Night_ForestBreeze", "夜風が森を撫でる", "Night breeze through trees"],
["ENV_Night_TwigCrack", "夜間の枝折れ音", "Branch cracking at night"],
["ENV_Night_MoonlitAmbience", "月夜の森の雰囲気", "Moonlit forest ambience"],
# 天気の環境音
["ENV_Weather_LightRain", "小雨の音／森", "Light rain in forest"],
["ENV_Weather_HeavyRain", "激しい雨の音／森", "Heavy rain in forest"],
["ENV_Weather_GentleStorm", "嵐の遠雷と強風", "Distant thunder and strong winds"],
["ENV_Weather_DripDrip", "葉から落ちる雨滴", "Rain drops falling from leaves"],
["ENV_Weather_SuddenDownpour", "急な豪雨／森", "Sudden downpour in forest"],
["ENV_Weather_AfterRain", "雨上がりの森の静けさ", "Post-rain forest calm"],
["ENV_Weather_MistGather", "朝靄が立ち込める", "Morning mist gathering"],
["ENV_Weather_DewDrip", "露の滴る音", "Dew dripping"],
["ENV_Weather_RainLeaves", "雨に濡れる葉音", "Rain-soaked leaves rustling"],
["ENV_Weather_ThunderRolling", "遠雷のゴロゴロ", "Rolling thunder"],
["ENV_Weather_WoodDrip", "倒木に溜まる雨水", "Rainwater pooling on log"],
["ENV_Weather_RainPitterPatter", "小雨のパタパタ音", "Pitter-patter of light rain"],
["ENV_Weather_ForestUmbrella", "葉が傘のように受ける雨音", "Leaves acting as rain umbrella"],
["ENV_Weather_GustyRain", "風を伴う激しい雨", "Gusty rain"],
["ENV_Weather_StormFade", "嵐の遠ざかる音", "Storm fading away"],
# 空気や風の環境音
["ENV_Air_GentleBreeze", "そよ風が葉を揺らす", "Gentle breeze rustling leaves"],
["ENV_Air_StrongWind", "強風が木々を揺らす", "Strong wind through trees"],
["ENV_Air_WhistlingWind", "狭い谷間の風音", "Whistling wind in glade"],
["ENV_Air_TreeSway", "大木の揺れる音", "Big tree swaying"],
["ENV_Air_ForestPulse", "風が通り抜ける間隔的な音", "Intermittent gusts"],
["ENV_Air_PineSway", "松林のざわめき", "Pine grove whisper"],
["ENV_Air_AirDrop", "突風の襲来", "Sudden gust"],
["ENV_Air_CalmHollow", "静かな林間の空気感", "Still air in hollow"],
["ENV_Air_SwirlingLeaves", "吹き飛ばされる落ち葉", "Swirling leaves"],
["ENV_Air_HighCanopyWind", "樹冠部の強風", "Canopy-level wind"],
["ENV_Air_ForestBreath", "森の息吹を感じる風", "Forest’s breath"],
["ENV_Air_MushroomSporeDrift", "胞子が舞う風", "Spore drift wind"],
["ENV_Air_ValleyBreeze", "谷間の涼風", "Valley breeze"],
["ENV_Air_EucalyptusSway", "ユーカリ林の風", "Eucalyptus breeze"],
["ENV_Air_ShadowWind", "日陰を通る涼風", "Shade wind"],
# 水流・川・滝の環境音
["ENV_Water_StreamTrickle", "小川のせせらぎ", "Trickling stream"],
["ENV_Water_RiverFlow", "川の流れる音", "Flowing river"],
["ENV_Water_LargeWaterfall", "大きな滝の轟音", "Roaring waterfall"],
["ENV_Water_SmallWaterfall", "小さな滝の水音", "Small waterfall"],
["ENV_Water_PondRipple", "池面のさざ波", "Pond ripples"],
["ENV_Water_WaterDrip", "洞から滴る雫", "Water dripping"],
["ENV_Water_BrookGurgle", "清流のゴボゴボ音", "Gurgling brook"],
["ENV_Water_RiverRapids", "急流の轟き", "Rushing rapids"],
["ENV_Water_FallMistySpray", "滝の水飛沫音", "Waterfall mist spray"],
["ENV_Water_LeafBoatFloat", "葉が水に浮く音", "Leaf floating"],
["ENV_Water_StreamCross", "浅瀬を流れる小川", "Shallow stream"],
["ENV_Water_ForestPuddles", "水溜りに当たる雨水", "Rain puddles"],
["ENV_Water_DistantCascade", "遠くの滝しぶき", "Distant cascade"],
["ENV_Water_RiverbankWind", "川岸の風と流れ音", "Wind and river flow"],
["ENV_Water_HollowDrip", "空洞を感じる雫音", "Hollow drip"],
# 動物の環境音
["ENV_Animal_DeerRustle", "シカの歩み音", "Deer moving"],
["ENV_Animal_BirdSongVaried", "多種の小鳥のさえずり", "Varied bird songs"],
["ENV_Animal_WoodpeckerDrum", "キツツキの連続突き音", "Woodpecker drumming"],
["ENV_Animal_FoxCall", "キツネの鳴き声", "Fox calling"],
["ENV_Animal_SquirrelChatter", "リスの鳴き声と動き", "Squirrel chatter"],
["ENV_Animal_BeeHiveBuzz", "蜂の巣の羽音", "Bee hive buzzing"],
["ENV_Animal_ButterflyLand", "蝶の着地音", "Butterfly landing"],
["ENV_Animal_FrogPondCroon", "池のカエルの合唱", "Frogs crooning"],
["ENV_Animal_BatFlutter", "コウモリの羽ばたき", "Bat flutter"],
["ENV_Animal_OwlWings", "フクロウの羽ばたき", "Owl wings"],
["ENV_Animal_DeerHoofDrum", "シカの蹄踏み音", "Deer hoofbeats"],
["ENV_Animal_InsectSwarm", "昆虫の群れの羽音", "Insect swarm"],
["ENV_Animal_HedgehogSnuffle", "ハリネズミの鼻鳴き", "Hedgehog snuffling"],
["ENV_Animal_EagleCry", "ワシの鳴き声／空", "Eagle cry"],
["ENV_Animal_MushroomMouse", "キノコネズミの動き", "Spore mouse rustling"],
# 効果音 (SFX_…)
# 足音の効果音
["SFX_Footsteps_LeafCrunch", "落ち葉を踏む足音", "Footsteps crunching leaves"],
["SFX_Footsteps_MuddyStep", "湿った土の足音", "Muddy step"],
["SFX_Footsteps_RockScuff", "小石を蹴る音", "Rock scuff"],
["SFX_Footsteps_MossPad", "苔を踏む柔らかな音", "Moss pad step"],
["SFX_Footsteps_BareWood", "倒木を歩く音", "Bare log walk"],
["SFX_Footsteps_GrassTread", "草を踏む音", "Grass tread"],
["SFX_Footsteps_SlowTread", "ゆっくり歩く足音", "Slow tread"],
["SFX_Footsteps_QuickTread", "素早く駆ける足音", "Quick tread"],
["SFX_Footsteps_WaterSplash", "浅い水たまりを踏む音", "Shallow splash"],
["SFX_Footsteps_StoneStep", "石畳を踏む音／林道", "Stone path step"],
["SFX_Footsteps_FallenBranch", "倒れた枝を踏む音", "Snap on branch"],
["SFX_Footsteps_MushroomStep", "キノコを踏むかすかな音", "Mushroom step"],
["SFX_Footsteps_SandTrail", "砂利道を歩く音", "Gravel trail"],
["SFX_Footsteps_HighSpeed", "全速力で駆ける足音", "Full sprint"],
["SFX_Footsteps_Sneak", "忍び足の静かな音", "Quiet sneak"],
# オブジェクト衝突／接触音
["SFX_Object_CrushLeaves", "葉を踏みつぶす音", "Crush leaves"],
["SFX_Object_BreakTwig", "小枝を折る音", "Break twig"],
["SFX_Object_RockDrop", "小石を落とす音", "Drop pebble"],
["SFX_Object_WoodKnock", "木に打ち付ける音", "Wood knock"],
["SFX_Object_StumpHit", "切り株を殴る音", "Stump hit"],
["SFX_Object_BarkPeel", "樹皮を剥がす音", "Peel bark"],
["SFX_Object_MushroomTear", "キノコを裂く音", "Tear mushroom"],
["SFX_Object_PebbleRoll", "小石が転がる音", "Pebble roll"],
["SFX_Object_RootSnap", "根っこを折る音", "Snap root"],
["SFX_Object_LeafTear", "大きな葉を破る音", "Tear leaf"],
["SFX_Object_BranchSwing", "折れた枝を振る音", "Swing branch"],
["SFX_Object_StoneHit", "石を叩く音", "Stone hit"],
["SFX_Object_TrunkThud", "倒木に何かぶつかる音", "Thud on log"],
["SFX_Object_VineSnap", "蔓を引きちぎる音", "Snap vine"],
["SFX_Object_PineconeCrunch", "松ぼっくりを踏む音", "Crunch pinecone"],
# その他の効果音
["SFX_Other_TwigSnap", "小枝が折れる音", "Small twig snapping"],
["SFX_Other_BirdAlarm", "警戒する鳥の鳴き声", "Alarmed bird call"],
["SFX_Other_FrogJump", "カエルが跳ねる音", "Frog jump"],
["SFX_Other_WaterSip", "小川の水をすする音", "Water sip"],
["SFX_Other_FireflyBuzz", "蛍の羽音", "Firefly buzz"],
["SFX_Other_SporeRelease", "キノコ胞子放出音", "Spore release"],
["SFX_Other_InsectStep", "昆虫の歩行音", "Insect step"],
["SFX_Other_DeerGrazing", "シカの食事音", "Deer grazing"],
["SFX_Other_BirdFlap", "鳥が飛び立つ羽ばたき", "Bird takeoff"],
["SFX_Other_WoodCreak", "急に軋む木音", "Sudden wood creak"],
["SFX_Other_PineconeDrop", "松ぼっくり落下音", "Pinecone drop"],
["SFX_Other_StreamSip", "小川の水飲み音", "Stream sip"],
["SFX_Other_BatScreech", "コウモリの鋭い鳴き声", "Bat screech"],
["SFX_Other_FoxRustle", "キツネの動く音", "Fox rustle"],
["SFX_Other_WindChimeLeaf", "自然の葉風鈴音", "Leaf chime"],
["SFX_Other_TwigShake", "小枝を揺らす音", "Shake twig"],
["SFX_Other_RainSplashLeaf", "葉に当たる雨しぶき", "Rain splash on leaf"],
["SFX_Other_BeeSting", "蜂の飛行から刺す音", "Bee sting motion"],
["SFX_Other_PondRippleTouch", "指で池面を撫でる", "Finger ripple"],
["SFX_Other_FungalPop", "キノコ胞子の小さな破裂音", "Fungal pop"],
["SFX_Other_BirdWingBrush", "鳥の羽が擦れる音", "Wing brush"],
["SFX_Other_DewCollect", "葉に溜まる露音", "Dew collect"],
["SFX_Other_CrabWalk", "森林のカニ歩き音", "Crab walk"],
["SFX_Other_MushroomThud", "大きなキノコを落とす音", "Mushroom thud"],
["SFX_Other_SquirrelNibble", "リスのかじる音", "Squirrel nibble"],
["SFX_Other_RustlingCloth", "旅人のマントが擦れる音", "Cloth rustle"],
["SFX_Other_LeafTumble", "落ち葉が転がる音", "Leaf tumble"],
["SFX_Other_SpiderWalk", "森のクモ這う音", "Spider crawl"],
["SFX_Other_RabbitHop", "ウサギのホップ音", "Rabbit hop"],
["SFX_Other_FoxHowl", "キツネの遠吠え", "Fox howl"],
["SFX_Other_DeerSnort", "シカの鼻鳴き", "Deer snort"],
["SFX_Other_LizardRustle", "トカゲの動く音", "Lizard rustle"],
["SFX_Other_BerryPick", "木の実摘み音", "Berry pick"],
["SFX_Other_BirdLanding", "鳥の着地音", "Bird landing"],
["SFX_Other_FrogDive", "カエルの飛び込み音", "Frog dive"],
["SFX_Other_OwlGlide", "フクロウの滑空音", "Owl glide"],
["SFX_Other_PineConeShake", "松ぼっくりを振る音", "Shake pinecone"],
["SFX_Other_RainLeafSlide", "雨に濡れた葉上滑走音", "Wet leaf slide"],
["SFX_Other_DeerHoofShake", "シカの蹄揺れ音", "Hoof shake"],
["SFX_Other_WoodChime", "木片が触れ合う音", "Wood chime"],
["SFX_Other_MushroomPick", "キノコ採取音", "Mushroom pick"],
["SFX_Other_WindLeafRustle", "風で揺れる葉擦れ", "Leaf rustle in wind"],
["SFX_Other_BeeWingBuzz", "蜂の羽音", "Bee wing buzz"],
["SFX_Other_BatLanding", "コウモリの着地音", "Bat landing"],
["SFX_Other_InsectTakeoff", "昆虫の飛び立つ音", "Insect takeoff"],
["SFX_Other_MouseScurry", "ネズミ走る音", "Mouse scurry"],
["SFX_Other_SwampBubble", "湿地の泡立ち音", "Swamp bubble"],
["SFX_Other_BirdPreen", "鳥の羽繕い音", "Bird preen"],
["SFX_Other_LeafWhip", "葉を鞭のように振る音", "Leaf whip"],
["SFX_Other_FlowerBloom", "花開く音", "Flower bloom"],
["SFX_Other_RustleDeep", "密集した葉擦れ音", "Thick rustle"],
["SFX_Other_CricketJump", "コオロギの跳躍音", "Cricket jump"],
["SFX_Other_FireflyGlide", "蛍の滑空音", "Firefly glide"],
["SFX_Other_MushroomRustle", "キノコ群生の擦れ音", "Mushroom cluster rustle"],
["SFX_Other_DeerAntlerTap", "シカの角を合わせる音", "Antler tap"],
["SFX_Other_BirchPeel", "カバの樹皮を剥く音", "Peel birch bark"],
["SFX_Other_WoodShave", "木を削る音", "Wood shave"],
["SFX_Other_LeafSlide", "葉上スライド音", "Leaf slide"],
["SFX_Other_BarkChop", "小さな樹皮を切る音", "Chop bark"],
["SFX_Other_TwigWhip", "小枝を鞭打つ音", "Twig whip"],
["SFX_Other_GrassSlice", "草をかき分ける音", "Grass slice"],
["SFX_Other_WaterLeafSip", "葉の水をすする音", "Leaf water sip"],
["SFX_Other_MushroomTap", "キノコを軽く叩く音", "Mushroom tap"],
["SFX_Other_TwigRoll", "小枝が転がる音", "Twig roll"],
["SFX_Other_LeafBounce", "葉が弾む音", "Leaf bounce"],
["SFX_Other_PineNeedleFall", "松葉が落ちる音", "Pine needle fall"],
["SFX_Other_RabbitNibble", "ウサギのかじる音", "Rabbit nibble"],
["SFX_Other_SquirrelJump", "リスの跳び移る音", "Squirrel leap"],
["SFX_Other_DeerFootSlip", "シカの滑る足音", "Deer slip"],
["SFX_Other_WoodSplit", "木が割れる音", "Wood split"],
["SFX_Other_RainCatcher", "葉の水受ける音", "Rain catcher"],
["SFX_Other_InsectFlutter", "昆虫の羽ばたき混在音", "Insect flutter"],
["SFX_Other_FrogChirp", "カエルの小さな鳴き声", "Frog chirp"],
["SFX_Other_PebbleSkip", "石を水面で跳ねさせる", "Pebble skip"],
["SFX_Other_LeafTearAside", "葉を横に裂く音", "Leaf tear aside"],
["SFX_Other_TwigStick", "小枝が何かに引っかかる", "Twig snag"],
["SFX_Other_MushroomCrush", "キノコを踏み潰す音", "Crush mushroom"],
["SFX_Other_LeafStepSoft", "柔らかな葉の足音", "Soft leaf step"],
["SFX_Other_BarkThump", "樹皮が打ち付ける音", "Bark thump"],
["SFX_Other_WindMurmur", "静かな風の囁き", "Wind murmur"],
["SFX_Other_ForestPulse", "森の脈動を感じる効果音", "Forest pulse"]
      ]

