# Common prompt to include for every sample
common_prompt = "High-quality, realistic sound"
title = "desert"

prompts = [
# --- 環境音: 昼間 (Daytime) ---
["ENV_Day_ScorchingWind", "焦熱の風／砂漠の日中", "Scorching wind in desert daytime"],
["ENV_Day_SandDuneRustle", "砂丘のざわめき／日中", "Sand dune rustling in daytime"],
["ENV_Day_HeatHazeAmbience", "熱気のゆらぎ音", "Heat haze ambience"],
["ENV_Day_CactusCreak", "サボテンの軋み", "Cactus creaking"],
["ENV_Day_RockHeatCrack", "熱せられた岩の割れる音", "Hot rock cracking"],
["ENV_Day_VultureCry", "ハゲワシの鳴き声", "Vulture cry"],
["ENV_Day_LizardScuttle", "トカゲの素早い走音", "Lizard scuttle"],
["ENV_Day_BarrenAmbience", "荒涼とした砂漠の環境音／昼", "Barren desert ambience—day"],
["ENV_Day_MirageDrift", "蜃気楼のゆらぎ音", "Mirage drift"],
["ENV_Day_SunBlister", "日射しの衝撃音", "Sun blister"],
["ENV_Day_OasisFaintBirds", "オアシスの小鳥のさえずり", "Faint oasis birdsong"],
["ENV_Day_DistantCamelCall", "遠くのラクダの鳴き声", "Distant camel call"],
["ENV_Day_CrackedEarthShift", "乾いた地面のひび割れ音", "Cracked earth shifting"],
["ENV_Day_SaharanAmbience", "サハラ砂漠の日中環境音", "Sahara daytime ambience"],
["ENV_Day_RovingBeetle", "砂漠甲虫の移動音", "Roving beetle"],
["ENV_Day_HeatRipple", "熱波のチル音", "Heat ripple"],
["ENV_Day_GoldenDuneGust", "金色の砂丘を渡る風", "Golden dune gust"],
["ENV_Day_TumbleweedRoll", "転がる藁玉／遠景", "Tumbleweed rolling—distant"],
["ENV_Day_CinderDry", "乾いた灰のざわめき", "Cinder dry rustle"],
["ENV_Day_DesertSunBeats", "強烈な日差しの脈動音", "Desert sun beats"],

# --- 環境音: 夜間 (Nighttime) ---
["ENV_Night_StarryAmbience", "星明りの砂漠環境音／夜", "Starry desert ambience—night"],
["ENV_Night_ColdBreeze", "冷えた夜風", "Cold night breeze"],
["ENV_Night_CricketChirp", "コオロギの鳴き声／砂漠の夜", "Crickets chirping—desert night"],
["ENV_Night_OwlHoot", "フクロウの遠吠え／夜", "Owl hooting at night"],
["ENV_Night_CoyoteHowl", "コヨーテの遠吠え", "Coyote howling"],
["ENV_Night_ScorpionRustle", "サソリの歩行音／夜", "Scorpion rustle—night"],
["ENV_Night_DesertAmbience", "砂漠全体の環境音／夜", "Overall desert ambience—night"],
["ENV_Night_MoonlitSand", "月光に照らされた砂のざわめき", "Moonlit sand rustle"],
["ENV_Night_DistantOasis", "遠くのオアシスの風音", "Distant oasis breeze"],
["ENV_Night_StarWindWhisper", "星を越えるそよ風", "Starlit wind whisper"],
["ENV_Night_RockChillDrip", "冷えた岩の滴音", "Chilled rock drip"],
["ENV_Night_RovingFox", "夜のキツネの足音", "Night fox steps"],
["ENV_Night_CamelBreath", "ラクダの息づかい／夜", "Camel breathing—night"],
["ENV_Night_PlanetaryQuiet", "宇宙的静寂感", "Planetary quiet"],
["ENV_Night_DuneEcho", "砂丘に響く微かな残響", "Dune echo"],

# --- 環境音: 天気 (Weather) ---
["ENV_Weather_LightDustDevil", "小規模な砂塵旋風音", "Light dust devil"],
["ENV_Weather_SandstormBuild", "砂嵐の接近音", "Sandstorm buildup"],
["ENV_Weather_HeavySandstorm", "激しい砂嵐の轟き", "Heavy sandstorm"],
["ENV_Weather_GustyDust", "風に舞う砂塵", "Gusty dust"],
["ENV_Weather_CalmBeforeStorm", "嵐前の静けさ", "Calm before storm"],
["ENV_Weather_HeatLightning", "砂漠の熱雷／遠景", "Heat lightning—distant"],
["ENV_Weather_RareRainDrip", "稀な雨滴音／砂漠", "Rare rain dripping"],
["ENV_Weather_AfterRainCalm", "雨後の乾いた静寂", "Post-rain calm"],
["ENV_Weather_SearingGale", "焦熱の強風", "Searing gale"],
["ENV_Weather_SandWhirl", "砂の渦巻き音", "Sand whirl"],
["ENV_Weather_BlindingDust", "視界を奪う砂塵", "Blinding dust"],
["ENV_Weather_StormFadeAway", "砂嵐が遠ざかる音", "Storm fading away"],
["ENV_Weather_DrySpark", "静電気のパチパチ音", "Dry spark"],
["ENV_Weather_CrackedEarthHeat", "熱せられた大地の放熱音", "Cracked earth heat release"],
["ENV_Weather_DustSettling", "砂塵が落ち着く音", "Dust settling"],

# --- 環境音: 空気/風 (Air & Wind) ---
["ENV_Air_GustyBreeze", "強風が砂丘を揺らす", "Gusty breeze over dunes"],
["ENV_Air_WhistlingThroughRocks", "岩間を抜ける風の笛音", "Whistling wind through rocks"],
["ENV_Air_IntermittentGusts", "断続的な風のうねり", "Intermittent gusts"],
["ENV_Air_DuneWhisper", "砂丘の囁き", "Dune whisper"],
["ENV_Air_SiroccoGust", "シロッコの突風", "Sirocco gust"],
["ENV_Air_CalmStillness", "静穏な砂漠の空気", "Calm stillness"],
["ENV_Air_SweepingWave", "砂の波動を乗せた風", "Sweeping sand wave wind"],
["ENV_Air_ShadowedGust", "岩陰を吹き抜ける風", "Shadowed gust"],
["ENV_Air_CanyonEchoWind", "渓谷に響く風音", "Canyon echo wind"],
["ENV_Air_HighAltitudeBreeze", "高地の涼風", "High-altitude breeze"],
["ENV_Air_WhirlingSand", "舞い上がる砂の音", "Whirling sand"],

# --- 環境音: 水 (Water) ---
["ENV_Water_OasisTrickle", "オアシスのせせらぎ", "Oasis trickle"],
["ENV_Water_SmallOasisRipple", "小さな泉のさざ波", "Small oasis ripple"],
["ENV_Water_DryStreamDryDrip", "干上がった小川のわずかな滴", "Dry stream drip"],
["ENV_Water_RareSpringFlow", "希少な泉の流れ音", "Rare spring flow"],
["ENV_Water_RainPuddleRustle", "砂地の雨溜まり音", "Rain puddle rustle"],
["ENV_Water_DistantMirageStream", "蜃気楼の小川音／遠景", "Mirage stream—distant"],
["ENV_Water_DewOnSand", "砂の露音", "Dew on sand"],
["ENV_Water_SaltFlatCrackle", "塩原のひび割れ音", "Salt flat crackle"],

# --- 環境音: 動物 (Animals) ---
["ENV_Animal_CamelFootfall", "ラクダの足踏み音", "Camel footfall"],
["ENV_Animal_CoyoteScurry", "コヨーテの走行音", "Coyote scurry"],
["ENV_Animal_VultureFeatherRustle", "ハゲワシの羽ばたき音", "Vulture feather rustle"],
["ENV_Animal_ScorpionStalk", "サソリの接近音", "Scorpion stalk"],
["ENV_Animal_SnakeHiss", "蛇のシューという音", "Snake hiss"],
["ENV_Animal_RattlesnakeRattle", "ガラガラヘビの警戒音", "Rattlesnake rattle"],
["ENV_Animal_DesertRodentRustle", "砂漠ネズミの走り音", "Desert rodent rustle"],
["ENV_Animal_DesertBirdCall", "砂漠小鳥の鳴き声", "Desert bird call"],
["ENV_Animal_OwlSilhouetteHoot", "砂漠のフクロウの鳴き声", "Desert owl hoot"],
["ENV_Animal_FennecRustle", "フェネックギツネの動き音", "Fennec rustle"],
["ENV_Animal_GilaMonsterShuffle", "ギラモンスターの這い音", "Gila monster shuffle"],
["ENV_Animal_RoadrunnerDash", "ロードランナーの駆け抜け音", "Roadrunner dash"],
["ENV_Animal_BeetleCrunch", "砂漠甲虫の殻音", "Beetle crunch"],
["ENV_Animal_LizardSlide", "トカゲの滑る音", "Lizard slide"],
["ENV_Animal_DesertFoxHowl", "砂漠キツネの遠吠え", "Desert fox howl"],

# --- 効果音: 足音 (Footsteps SFX) ---
["SFX_Footsteps_SandWalkSoft", "柔らかな砂を踏む足音", "Soft sand walk"],
["SFX_Footsteps_SandWalkHeavy", "重い砂を踏む足音", "Heavy sand walk"],
["SFX_Footsteps_RockyStep", "岩石を踏む足音", "Rocky step"],
["SFX_Footsteps_TumbleweedKick", "藁玉を蹴る足音", "Tumbleweed kick"],
["SFX_Footsteps_CrunchingGravel", "砂礫を踏むカリカリ音", "Crunching gravel"],
["SFX_Footsteps_ShallowPuddleSplash", "浅い水たまりを踏む音", "Shallow puddle splash"],
["SFX_Footsteps_BareSandRun", "裸足で駆ける音", "Barefoot sand run"],
["SFX_Footsteps_LeatherBootDrum", "革靴で歩く重い音", "Leather boot drum"],

# --- 効果音: オブジェクト衝突／接触 (Object SFX) ---
["SFX_Object_RockDrop", "小石を落とす音", "Drop small rock"],
["SFX_Object_CactusPrick", "サボテンに触れる棘音", "Cactus prick"],
["SFX_Object_TumbleweedRollImpact", "転がる藁玉が当たる音", "Tumbleweed roll impact"],
["SFX_Object_SnakeScaleBrush", "蛇の鱗が触れ合う音", "Snake scale brush"],
["SFX_Object_PebbleSlide", "小石が転がる音", "Pebble slide"],
["SFX_Object_LeatherStrapRustle", "革ベルトの擦れ音", "Leather strap rustle"],
["SFX_Object_CanteenLatch", "水筒の蓋の開閉音", "Canteen latch"],
["SFX_Object_WoodenBoxClack", "木箱の蓋を打つ音", "Wooden box clack"],

# --- 効果音: その他 (Other SFX) ---
["SFX_Other_ThirstQuenchSip", "喉を潤す水音", "Thirst quench sip"],
["SFX_Other_CampfireIgnite", "キャンプファイヤー点火音", "Campfire ignite"],
["SFX_Other_CampfireCrackle", "焚き火のパチパチ音", "Campfire crackle"],
["SFX_Other_CanteenShake", "水筒を振る音", "Canteen shake"],
["SFX_Other_MapUnfold", "地図を開く音", "Map unfold"],
["SFX_Other_CompassClick", "コンパスのクリック音", "Compass click"],
["SFX_Other_GemClink", "宝石が触れ合う音", "Gem clink"],
["SFX_Other_SunMirrorFlicker", "鏡で光を反射する音", "Sun mirror flicker"],
["SFX_Other_DistantCaveBreeze", "遠くの洞窟からの風音", "Distant cave breeze"],
["SFX_Other_StarlightChime", "星明りのチャイム音", "Starlight chime"],
["SFX_Other_ElectricSandZap", "砂に帯電する電気音", "Electric sand zap"],
["SFX_Other_MysticRuneHum", "古代文字の低い響き", "Mystic rune hum"],
["SFX_Other_SpellSandSwirl", "魔法で砂が舞う音", "Spell sand swirl"],
["SFX_Other_PhoenixCry", "フェニックスの叫び声／幻想", "Phoenix cry"],
["SFX_Other_GoldenKeyUnlock", "黄金の鍵で開錠する音", "Golden key unlock"],
["SFX_Other_AncientDoorCreak", "古代の扉の軋み音", "Ancient door creak"],
["SFX_Other_ShieldClang", "盾を構える金属音", "Shield clang"],
["SFX_Other_ArrowNock", "矢を弓に装填する音", "Arrow nock"],
["SFX_Other_BoltRelease", "弩を放つサウンド", "Bolt release"],
["SFX_Other_SandTimerFlip", "砂時計をひっくり返す音", "Sand timer flip"],
["SFX_Other_DustOffArmor", "鎧の埃を払う音", "Dust off armor"],
["SFX_Other_GlassBottleClink", "瓶が触れ合う音", "Glass bottle clink"],
["SFX_Other_DistantTempleChant", "遠くの神殿の詠唱", "Distant temple chant"],
["SFX_Other_MagicPortalOpen", "魔法の門が開く音", "Magic portal open"]
      ]

